---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Content
- type: document
  path: src/index.md
  label: Homepage
  templates:
  - homepage
- type: document
  path: src/genius.md
  label: Genius Immersive Experience
  templates:
  - genius
- type: heading
  label: Globals
- type: document
  path: src/_data/navigation.json
  label: Homepage navigation
upload_dir: src/images/upload
public_path: "/upload"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - ELEVENTY_ENV=staging
  - NPM_VERSION=7
  preview_output_directory: src/dist
  install_dependencies_command: npm install
  preview_docker_image: node:14
  mount_path: "/srv"
  working_dir: "/srv/src"
  instant_preview_command: npm start
